version: "3.9"

services:
    php:
        container_name: php
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        entrypoint: composer
        working_dir: /public
        ports:
            - "8080:80"